language: node_js
node_js: 6
cache:
  directories:
  - node_modules
  - bower_components
  - "${NVM_PATH}_modules"
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
- npm install -g bower polymer-cli
- bower install
script: echo "Deploying!"
before_deploy: polymer build
deploy:
- provider: firebase
  skip_cleanup: true
  on:
    branch: master
  project: devfestkl16
  token:
    secure: "Qdbs3ZW8lP8XvQA7w1LnwvTuwvuqD2g1jKE1/9F66T/s9SotWHbtqGZGTJNS/f6ZpUvRxXg/t95RkS0PIA8evx5/zyGpjnMt7DXoOPHWG5u4kKnh377kfWRBk95mLGCUoftEn9RzKYe2lrbrZezPbvIL8A35HoCPU3PxHUu7cXg+ds4a7yJoqIOBuOIJm+TO4DbmLM5i6R9A2tyyCSQtH6y2+epMrJRbF3F3i9y35zH67EbpQUnjt5DFxrNhibav/3oWl/QL2ydWHXRW71945aNJWMHiECw7oLHN2aghRhVcpgU6RdwrQ0F129zCZ1S3tiVX9o0wK6xY/ElODyWY0zvtO6noMA7OuztRwav7oY0Ybhujx82wIgWi6SW1ZaunOZUpCCQ8eBj14rBPdlgU9K6IcsHUzPNToNtQFvpr/g+t3WK94krJAtT4qdKBpPaH3iyvlbXNKnJa+ssT30Gh1ODGvKV0ERioV0LCo15SYQ8x1PN1cIy9FyIcr0pbtQeYxQJgIVHFBTEomAQT0pd1IN7n8YxPVMYBEPOMij08ewT/xPhWzM0UqlqGlBd9KBt7g/vA+Q5yH5e8MHvEaBX4mA9moW+9EZjSAmOC2O3IbYRv/edHAwq3Y/saUWH8GRRq9r5NG93GsWhMUCsdxfKtvA011gZpuBj/+ZPlDXzWee8="
